leftnav:
- identifier: 6de678fd-f542-ae23-9de0-55d7b2f9baa1
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 10
- identifier: external-a2b8ab50032a470e98db3c0b6204695e
  name: Online Publication
  url: https://openlearninglibrary.mit.edu/courses/course-v1:OCW+18.031+2019_Spring/about
  weight: 20
